language: python
python:
  - "3.6"
cache: pip

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry config virtualenvs.create false
  - poetry install --verbose

script:
  - poetry run black --check .
  - poetry run pytest -vvv tests
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    branch: master

notifications:
  email: false
